### ISSUE TITLE
Mechanics

### ISSUE THREAD

**Issue by jennybc** [ShanEllis/datasharing_TAS#1]
This is the beginning of my AE review. I will presumably be opening some more issues as I go.

I'm not entirely clear re: your mechanics. I think the `.md` is the core source document? I think it probably has to be `.Rmd` to take advantage of that yaml? But somehow I think the `.markdown_github` is derived from that. If that had `.md` as extension it would be more readable on GitHub.

Anyhow, I've forked and brought everything to my local machine and am reading the `.html` as committed. `.html` is unreadable on GitHub, so it would be great to focus on a definitive `.md` file for GitHub readability. (These processes are all part of *my* contribution to this issue!).

These mechanical issues may soon be moot, but you might want to sharpen this up if this repo lives on and maybe is useful for future (?). Close this whenever you feel like it.

**Comment by ShanEllis** [comment]
I _think_ I've formatted a little more appropriately, but will fully address once taking care of yaml is possible.

**Comment by ShanEllis** [comment]
Uses rticles yaml now.
