### ISSUE TITLE
Consider citing White et all

### ISSUE THREAD

**Issue by jennybc** [ShanEllis/datasharing_TAS#12]
It's entirely your call. But this might be a good paper to put on people's radar:

-   Nine simple ways to make it easier to (re)use your data by EP White, E Baldridge, ZT Brym, KJ Locey, DJ McGlinn, SR Supp. *Ideas in Ecology and Evolution* 6(2): 1–10, 2013. <doi:10.4033/iee.2013.6b.6.f> <http://library.queensu.ca/ojs/index.php/IEE/article/view/4608>

**Comment by ShanEllis** [comment]
Thanks for putting it on our radar. Somehow we had completely overlooked this paper. Added to first sentence.
