### ISSUE TITLE
Response to review from https://github.com/stephenturner

### ISSUE THREAD

**Issue by jennybc** [ShanEllis/datasharing_TAS#13]
https://github.com/jtleek/datasharing/issues/473

**Comment by jennybc** [comment]
Having read this, it seems like this has mostly been addressed. But I'd still appreciate one of the authors addressing that here and making sure there aren't any loose ends that need tying up.

**Comment by ShanEllis** [comment]
First, thank you @stephenturner for such thoughtful comments made previously [here]
 (https://github.com/jtleek/datasharing/issues/473)!

**re: major revisions**. We took all suggestions into account. To summarize here, the newest draft:
- expands target audience to include those suggested
- changed intro to remove confusing sentences
- clarifies what raw data is and is not
- includes Box1 idea (and references Karl Browman)
- changed our example from RNA-Seq to a more general example for all audiences. Thanks for the suggestion! 
- expands out the code book section and includes a figure to explain a little better what we mean there
- have included Good Enough Practices reference (although we have not changed our language...despite loftiness)

Note: We did not discuss file management here (despite agreeing that it is critically important!) as it fits in less with the theme here. We'll leave that topic for others to tackle. 

**re: minor revisions**
- format has been formalized; will be further updated to meet journal specifications
- Wording has been formalized throughout
- included 'data dictionary' as an alternative to code book
- included a lot of the 'why' suggestions in 'Box 1' idea
- added text suggestions
- fixed row names --> column names error
