### ISSUE TITLE
Good Enough Practices reference

### ISSUE THREAD

**Issue by jennybc** [ShanEllis/datasharing_TAS#14]
This should have a proper citation any day now in PLoS Comp Bio. Let's leave this open as a reminder to update your bib. Hopefully the timing works out before this train leaves the station.

**Comment by jennybc** [comment]
Manuscript was formally accepted today and is in production. So likely I can provide better citation very soon.

**Comment by ShanEllis** [comment]
Congrats! Will update citation as soon as it's possible.

**Comment by ShanEllis** [comment]
updated on both PeerJ and TAS submission
