### ISSUE TITLE
all things completed on our end (for now?)

### ISSUE THREAD

**Issue by ShanEllis** [ShanEllis/datasharing_TAS#15]
Just checking in to make sure we've addressed everything possible on our end? If there's anything we've missed or you'd like to see, please let me know!

**Comment by jennybc** [comment]
I think you just need to do #8 then please submit to TAS! Let me know when you've done so by closing this.

We'll leave #14 open in case a better citation becomes available during the remaining TAS process.

**Comment by ShanEllis** [comment]
submitted! Thanks for all your help!

From README of dsscollection, looks like there is no issue with us submitting this to bioRxiv as well. Please let me know if I misunderstood/if there is any issue with us doing so.

**Comment by jennybc** [comment]
There is a plan to submit to our own to-be-launched PeerJ collection. Will that serve your preprint needs? If so, why don't you wait til we coordinate that. Just after we get everything into TAS system.
