### ISSUE TITLE
"data sharing" can mean many things

### ISSUE THREAD

**Issue by jennybc** [ShanEllis/datasharing_TAS#2]
Apologies in advance for my stream-of-reading micro-issue approach here.

"Sharing": you are really talking about literally transmitting data to a collaborator. I hope somewhere I'll find wording that makes a distinction between this and sharing the data behind a published paper with the community. Depositing it in a suitable long-term repository, etc.

If I see that clearly, I'll close this myself.

If I do not, please consider this a request to add that somewhere fairly early. Your length is quite good, so you can afford to add it.

**Comment by ShanEllis** [comment]
Text added to end of first paragraph of introduction to this point.
