### ISSUE TITLE
Get rid of as many `/` as you can

### ISSUE THREAD

**Issue by jennybc** [ShanEllis/datasharing_TAS#3]
E.g.

> to analyze data with/for them

> whose job it is to collate/clean/wrangle data sets

I use `/` all the time myself. But can you take a pass through and try to turn these into `/`-free sentences? 

Concrete illustration with above examples:

> to analyze data with or for them

> whose job it is to collate, clean, and wrangle data sets

**Comment by ShanEllis** [comment]
Oh man, there sure were a lot more of these than I realized - good catch. All have been removed in updated draft, except for: (Mac/Windows/Linux)
