### ISSUE TITLE
Do you really want people to tidy the data?

### ISSUE THREAD

**Issue by jennybc** [ShanEllis/datasharing_TAS#4]
If data generator has not already done so, do you really want them to do this step?

1. The raw data. --> 2. A tidy data set

Even that means them mousing around in Excel?

If so, carry on. If you have any caveats to add, go for it!

**Comment by jennybc** [comment]
> When you turn over a properly tidied data set it dramatically decreases the workload on the statistician and minimizes the likelihood of errors during analysis

Ok here it is again, so I guess you really do mean it!

**Comment by jennybc** [comment]
Maybe these "spot checks" you mention are the key. The statistician *does* want the data generator to tidy the data, by whatever means necessary, but then does some checks of raw vs tidy to make sure it was done correctly? And the overall time savings pays off?

**Comment by ShanEllis** [comment]
Jeff and I agree that the overall time savings pays off _and_ that there are cases in which the data generator simply knows more about the data than we do, making tidying on their end helpful. However, I _definitely_ see where your hesitation is coming from. We, of course, ask for the raw and the tidy (in case of errors in tidying). We have added language to emphasize that spot checks are really important point ....to try to minimize tidying gone wrong scenarios in section 2.2:

"Spot checking data after tidying, which includes, but is not limited to, ensuring the correct number of columns and rows are present and that column labels are accurate and consistent across spreadsheets, is crucial."

**Comment by jennybc** [comment]
OK. I think we're done on this one.
