### ISSUE TITLE
Are these citations or ??

### ISSUE THREAD

**Issue by jennybc** [ShanEllis/datasharing_TAS#5]
> The strange binary file (“Binary File” 2017) your measurement machine spits out
> The complicated JSON (“JSON” 2017) data you got from scraping the Twitter API (“Twitter API (@Twitterapi) Twitter” 2017)

Can you help me understand what these are: (“Binary File” 2017), (“JSON” 2017), (“Twitter API (@Twitterapi) Twitter” 2017)? Are they destined to be citations?

**Comment by jennybc** [comment]
I'm beginning to gather that these *are* citations, based on other similar things.

We do need to push to a formatted version of this ASAP, which comes back to #1. I know @hadley has made the necessary rticles template, so perhaps you should switch straight to the format we'll need for TAS submission.

**Comment by ShanEllis** [comment]
@jennybc, I'm coming up short. Happen to know which rticles template I should use? Will format accordingly ASAP.

**Comment by jennybc** [comment]
Subscribe to this issue:

https://github.com/dsscollection/dsscollection/issues/39

where I think some details re: the articles template will appear soon. Suggest you hold off on this until we make that more clear.

**Comment by ShanEllis** [comment]
will hold off for now. Also, if it possible, mind sending link again -- I'm unable to subscribe to that issue (page not found?)

**Comment by jennybc** [comment]
I just invited you to join the dss Organization and the authors team. Once you accept, you should be able to see that issue. But here's the most important info:

To use the TAS rticles style:

1. Install the dev version of rticles from github:
   
   ```R
   # install.packages("devtools")
   devtools::install_github("rstudio/rticles")
   ```

1.  Set the asa style in your YAML metadata

   ```yaml
   output: 
   - rticles::asa_article
   - github_document
   ```

This will generate a pdf, as well as the tex file to submit to TAS.

**Comment by ShanEllis** [comment]
Thanks!. I am now able to see issue and have used the TAS rticles style. Two issues (and I can open them over in dsscollection if they're actual issues and not just things I'm missing):
1. Citations for non-articles (@misc tags) not working. I've removed the [@...] and left citation as [...] for now. 
2. I may be missing it, but should figures be kept separate (as they are now)? Or should I include and reference them as I would in a LaTeX document? Or formatted some other way?

**Comment by ShanEllis** [comment]
Oh, and I forgot.
1. What is the correct fomatting for inclusion of more than one affiliation for a single individual?

**Comment by jennybc** [comment]
Here's a `@misc` entry in my bib that seems to be working fine, in case that helps:

```
@misc{git-for-humans,
  Author = "Alice Bartlett",
  Title = "Git for Humans",
  Institution = "Financial Times, London",
  Howpublished = "Talk at UX Brighton",
  Year = "2016",
  Url = "https://speakerdeck.com/alicebartlett/git-for-humans",
  Abstract = "This talk will explore a tool that most developers couldn't live without. We'll look at the way it helps developers tell the story of their project, and how non-technical people can get in on the action too."
}
```

About the figures ... I'd have to read TAS instructions for authors myself. Can you do that? Otherwise do what you prefer and see if they accept. I'm eager to just get these flowing into their system and realize there may be a few formatting requests. We've already got at least 3 submitted, so this is promising.

Re: multiple affiliations, here's how I described myself in my piece:

```yaml
authors:
- name: Jennifer Bryan
  affiliation: |
    RStudio and the Department of Statistics, University of British Columbia
```

**Comment by ShanEllis** [comment]
Thanks, @jennybc! Citations all fixed now. (Wikipedia citations were removed where unnecessary / changed where appropriate.) Thanks for the working @misc{} example. 

Multiple affiliations now included.

And figures included in line as suggested by TAS. But, I understand further formatting may be required.

**Comment by jennybc** [comment]
I regard this as closed on our end. I'm sure we'll find out if TAS has additional formatting requests.
