### ISSUE TITLE
You know the raw data are in the right format if you ...

### ISSUE THREAD

**Issue by jennybc** [ShanEllis/datasharing_TAS#6]
Great paragraph and great point. I am amazed at how many people "helpfully" take averages for me and just want to give me those, instead of burdening me with the raw data. I want to ask them: what exactly do you think it is I do for a living?

You could mention this example of people trying to be helpful (= providing summary statistics instead of raw data), but in fact being the opposite. Or not. Do as you wish.

**Comment by ShanEllis** [comment]
Great idea. This example has been added to the raw data section.
