### ISSUE TITLE
Separate workbooks vs separate worksheets

### ISSUE THREAD

**Issue by jennybc** [ShanEllis/datasharing_TAS#8]
I made the same comment on the spreadsheet org piece by @kbroman and @karawoo!

> the tidy data should be in one Excel file per table. They should not have multiple worksheets

I push back on this but am happy if no one changes their article. But I just want to be on record in support of multiple worksheets in one workbook for storing the different types of data = different tables. Keeping them in the same workbook keeps them together and every package that reads xls or xlsx can address different worksheets.

Feel free to close, regardless of whether you make an edit.

**Comment by jennybc** [comment]
Maybe you should cite Broman, Woo paper. We need to figure out how to do such cross-citations 🤔.

**Comment by ShanEllis** [comment]
re: citing Broman/Woo, I was previously citing http://kbroman.org/dataorg/ ....didn't realize it's been extended here: https://github.com/kbroman/Paper_DataOrg ...but I don't quite know how to address this. Leaving open, as I agree...we will still need to figure out citations.

**Comment by jennybc** [comment]
Can you just do something to cite Broman/Woo from this issue? Use `@misc` or whatever you need to? We will get a definitive answer.

**Comment by jennybc** [comment]
Here's their repo, so you can grab proper title, etc.

https://github.com/dsscollection/data-org-spreadsheets

You should be able to see it now that you're in the dss org.

**Comment by ShanEllis** [comment]
citation updated to peerJ preprint
